insert into accounts (username, password, university) values ('Judie', '$2b$10$YTOOZAxV9C6uAcefPmcfzeFWk0X0.BlZVAQ/leyd46StVL9QguGQu', 'Catholic University of Malawi');
insert into accounts (username, password, university) values ('Bron', '$2b$10$W0WpgsEBf3G9QCjTsv4nGe.n4BQlNIGPWBmzW//NRR8PEkYbK1zd.', 'Tokyo Woman s Christian University');
insert into accounts (username, password, university) values ('Dill', '$2b$10$C9fJ.Q6Q8pffjoI2fUwI5uSO1f3IZT5HqPrzE19gJHMfcYvnp2.dC', 'University of Wisconsin - Milwaukee');
insert into accounts (username, password, university) values ('Erin', '$2b$10$J/4ATRWxe6gw7HNEAXNl2umBSKQSGlEUWw0zQHaIzXdBSCJe/fccC', 'Creighton University');
insert into accounts (username, password, university) values ('Elden', '$2b$10$AhT0.Edu9o5UYMx1yupID.aIeMOYuCu4nZgjxoqFby4LQJ4NZ0sTq', 'Hochschule für Technik und Wirtschaft Karlsruhe');
insert into accounts (username, password, university) values ('Morrie', '$2b$10$QdxOm1cMxGSrhk.Kckju8.p1jVEDoxK27xRU5K0QmfHa49QlfLNwm', 'Universität Hildesheim');
insert into accounts (username, password, university) values ('Brnaba', '$2b$10$HWS4betEBSJbPydIiTX1j.UmmKpOdVxkPYeOTE9LVCNEY3zUD1nxq', 'Yanbian University of Science and Technology');
insert into accounts (username, password, university) values ('Patty', '$2b$10$9a0VWgvDwBNvcRqrxloyLehfczLwQXQcWPE0VX8QZclx6Q8JJfiOW', 'Campus Bio-Medico University of Rome');
insert into accounts (username, password, university) values ('Neville', '$2b$10$DiGqvcDXfm8lEIUouVtQzexaYOwoRDnxjKVp0NMdyILw.0OegU.z2', 'Nagasaki Institute of Applied Science');
insert into accounts (username, password, university) values ('Alica', '$2b$10$F5Yvots7FAlUTdtht8G/QuxSmBBq98LlvAgEUtWf5huulshLMs5s6', 'Palacky University');
insert into accounts (username, password, university) values ('Rahel', '$2b$10$W1qt8Kn2gm9pmLC6EzkQlu8Ql6hHYkYkCvF69GwujRI0/uX3u6zc2', 'Vaasa University of Applied Sciences');
insert into accounts (username, password, university) values ('Wilbert', '$2b$10$wuUCm58ggQFLZQ0LejvsuehjZLJ0A.1U98FxaFwZ.1Qnj4vJ7T.l6', 'Kyonggi University');
insert into accounts (username, password, university) values ('Bjorn', '$2b$10$YfukdbfKMWdgjIeOGw7UDujOQKsXpLGPrC5UUKYFKQCOq2sFzyEN.', 'Oklahoma State University - Tulsa');
insert into accounts (username, password, university) values ('Granville', '$2b$10$MSoDhkyuy7lGVZbkDC68A.4JPr7oudhlvPetH.gzedtYiaiap1QAq', 'Kurashiki University of Science and the Arts');
insert into accounts (username, password, university) values ('Aileen', '$2b$10$LiG7.SMiFZtcS1W03dG0IudW/LEnKPoP9oDv1PDUl0FfNkwQGDqOO', 'South China Agricultural University');
insert into accounts (username, password, university) values ('Sid', '$2b$10$47WH5nykwFyh3n72CauMSe2fYhfi5y0sNyfYBdoLCBuV3FpDS.Hxa', 'Ecole Nationale Supérieure de Chimie de Clermont-Ferrand');
insert into accounts (username, password, university) values ('Traver', '$2b$10$CbuUMz2pYTRZoiX.Vh0qhO3xap3CAEQfPOhwKPClZcBMCFi/EzSIS', 'Dartmouth College');
insert into accounts (username, password, university) values ('Curran', '$2b$10$xLoR.XeQq27T9FWCzfZ0meykBX7KYcmfxjhc9Rt28O6RWmZU4m6AS', 'Universitas Pasundan');
insert into accounts (username, password, university) values ('Ardelle', '$2b$10$KfT7nSWQVIF3ylAz8aoG6Ohdbcf1FSOnZRrMZ6PrPbaFOn503B1rC', 'Ferrum College');
insert into accounts (username, password, university) values ('Courtney', '$2b$10$8M96i0QLBbdVWU8Ne4stv.KO9cDiFgW6ESwW.zi3wEG3Jq0odnQx6', 'Xinjiang Agriculture University');
insert into accounts (username, password, university) values ('Sergio', '$2b$10$qq4vrBsIBQRb.Y8ZA0TS6e8NGQlB57.5FGJYdUCJA3i9ZgPtLbmuW', 'Nivadhana University');
insert into accounts (username, password, university) values ('Margo', '$2b$10$/0IQ3XeLR3WJqo.WDVBxTu0wC2Kkv0Rhyr1Jq8.VLtRATwPXkAbKy', 'Abai State University');
insert into accounts (username, password, university) values ('Lanna', '$2b$10$xri5R4VCR0seXMKBoJAEqe6DOox9erILA9RaHviHIDOgKvEKblxEi', 'Universidad de Guanajuato, Campus León');
insert into accounts (username, password, university) values ('Yanaton', '$2b$10$AVO561OhoBz1OhjK6eFGRebM22fE.00Vryh2/CRamM4VjEQn1fRKy', 'Africa University');
insert into accounts (username, password, university) values ('Camilla', '$2b$10$cMjT6DUC174e0nWJbLTyYOwt25UuG3u1swo6eyYhg9euCmif2ayze', 'Shikoku Christian College');
insert into accounts (username, password, university) values ('Moise', '$2b$10$KsgM0IvFoMIgV2tmdotZye/DnytwRE7pnNfz1sznYmvsRDOih5IUu', 'Université de Chlef');
insert into accounts (username, password, university) values ('Jenilee', '$2b$10$GW.KoUEOLBajTDBG.Id/6eS4qzRkkrL5jVLKuBSptJ8qBGvCb5AYy', 'Pedagogical University of Krakow');
insert into accounts (username, password, university) values ('Conny', '$2b$10$fSkGNqF.WkcPqgpQ6dxBcOunL8GyM74tn2WncpuTM/Z2txxxB2MNC', 'Instituto Politécnico de Leiria');
insert into accounts (username, password, university) values ('Harold', '$2b$10$k98OYRbWB.U.cQcugiKNBeo5QOVT6M76wwa2x12YTI4y0cuGrIzA6', 'Greensboro College');
insert into accounts (username, password, university) values ('Brunhilda', '$2b$10$ZI2ohiGv0ZOin9XP6M8iXuOP5cbwsm089CigxNhiC4hf9h.CZFR0q', 'Universite Amadou Hampaté Ba');
insert into accounts (username, password, university) values ('Damien', '$2b$10$q6XMeZgsWyeaP5DAuKDGQeYTO0wYFhr7U8zx6jXgsJgNIy/Yz67Gy', 'American-European School of Management ');
insert into accounts (username, password, university) values ('Karlotte', '$2b$10$IwKg4o8pzPwlpkNiCjn2WO2iDFvPF9f2IdfrDyIz2CJFFfhEB4AHm', 'University of Osijek');
insert into accounts (username, password, university) values ('Borg', '$2b$10$OhPEEWGUGr3atVhAy760gOhGb4QfXm285ldFtPVwFJalfmxw95vjW', 'Universidad del Noroeste');
insert into accounts (username, password, university) values ('Dill', '$2b$10$fgOrH//fUmnHeFc8S8Lx0ObM03W0a2kEDZVQcZI2Kg2lAHGaNRlDK', 'Institut Catholique d Arts et Métiers Lille');
insert into accounts (username, password, university) values ('Jayme', '$2b$10$3K/7gjT4ug0kh9D0zCIKWOR8hCAk//dGQMx9wDqbmnSqLFXm2/9Em', 'University of Northampton');
insert into accounts (username, password, university) values ('Lian', '$2b$10$cDG/H3rsX0ndrMbbagplXOSXcMKy9KUdAq2Qh8ECkjBxn1bPsq3qC', 'Saint Louis College');
insert into accounts (username, password, university) values ('Rheta', '$2b$10$3N033WMyYPbgsOXz.cD/WeACrWDlWPcXQnsoAmC5XcDVhA1tRUvMu', 'Kerala University of Fisheries and Ocean Sciences');
insert into accounts (username, password, university) values ('Linus', '$2b$10$prd6KkxmG2zMqerWzmKWEe3qV2k0AQOqOUl5xUKppDFAoIDsdTHhy', 'Torbat Heydarieh University of Medical Sciences');
insert into accounts (username, password, university) values ('Luz', '$2b$10$lwTDfP5vN6OUdJ86cGDdnOePiHXlYJw41X/UBg1iYl80gO6TG7k42', 'Academy of the Ministry of Internal Affairs of the Republic of Belarus');
insert into accounts (username, password, university) values ('Bobbie', '$2b$10$zgksQIpsL42Rk1sxeam72./TLxTFtAnJH3uurRQ/V2pohc8o/8g7y', 'Koya University (Kurdistan Region)');
insert into accounts (username, password, university) values ('Adelheid', '$2b$10$K9hJ3szNrfRWM3Sx.2Xx8.93dgQ0KzVgmdA3BXT/hQAn.dZ5Smdr2', 'Ball State University');
insert into accounts (username, password, university) values ('Erminia', '$2b$10$f3AuZfhybROBAkzWxapSGehIngISVEKpNmy0gIaB6XZHp.lI8zJgy', 'Hungarian Academy of Fine Arts Budapest');
insert into accounts (username, password, university) values ('Mace', '$2b$10$D0prk9jNWUKeU0wQaLI.QuMK64w5efFDN6NhXl2fe9A6QfJipqiei', 'Bodo Regional University');
insert into accounts (username, password, university) values ('Mollee', '$2b$10$9iH00JYAVrmmul1q84SxyOWknIJ0V3fNnZFxwY1Kgi7Y2Uj3cGXle', 'Universität für Musik und darstellende Kunst Graz');
insert into accounts (username, password, university) values ('Pamella', '$2b$10$ljZ1Mrzk4XLoFV4H81AYwOpqPzjnVAsHrIWRyHT8BpwilxlTkiwI6', 'Aichi University of Education');
insert into accounts (username, password, university) values ('Nanette', '$2b$10$ejPfS2hHRRJ6yxpUM4pN/Ol41r05fA8JnFX0YphcEt8tWS23XBmha', 'Global Open University , Nagaland');
insert into accounts (username, password, university) values ('Nealon', '$2b$10$qE3gNhYDgamdDTFdQ5ic7ueyZxEMDxtNLdLKeQnW9aOquSryoFFV.', 'Sarajevo Film Academy');
insert into accounts (username, password, university) values ('Isabella', '$2b$10$T9sS4Yqe1L6CzmxNGbDjaufjFUrYiPdR4dTPoaILhM.UOZpk4WHQa', 'Universidad San Francisco Xavier');
insert into accounts (username, password, university) values ('Orelee', '$2b$10$W4XjV.kN3NkHdNeHH3pBXeMu3liGxjxqiB14oRKPTonV2CW7AFlGO', 'Humboldt State University');
insert into accounts (username, password, university) values ('Oliver', '$2b$10$0eL5iWlk3ONE7w9/0MD8N.VuDKtDKH.t6vdKiDdzZeg2e7mcnejsG', 'Hunan University');
insert into accounts (username, password, university) values ('Mayne', '$2b$10$ha5mFcwE117e5eAY7Kbv7OM3DYHredKDpJ/ZRptc6.pTC6qaFCoxq', 'Missouri Southern State College');
insert into accounts (username, password, university) values ('Faye', '$2b$10$5LNJto8V3ONFZoyyeJRpt.1ht6vOe26rGCyQm1Mg4GjOp4fc7hYP2', 'Polytechnic University');
insert into accounts (username, password, university) values ('Rabi', '$2b$10$6i1qoBdHZxROkyMGIt/FI.KQr6N9Hf59UHEAC0ghUQHnEIyZdUEAK', 'Universidad de La Coruña');
insert into accounts (username, password, university) values ('Budd', '$2b$10$/9i3YTFBa93NKehITcN1UeqZDKWzJ10YyTz6Z7bEqW7DhKWSRGJM2', 'İstanbul Şehir University');
insert into accounts (username, password, university) values ('Kaylee', '$2b$10$dVSISvjmyUJUKE6m9A3kwersEwVFkrx8Bm2X9uVewGJkfWh6nyQuq', 'Dalian University of Foreign Language');
insert into accounts (username, password, university) values ('Vidovik', '$2b$10$pWTqTrKxGp79UZpstzLWWO59CsM9Y3t.gCB0rj6Ni4NohilZJ1f1m', 'Visva-Bharati University');
insert into accounts (username, password, university) values ('Edsel', '$2b$10$jYe3j7et8xeUwVN0.9kKHOANZxRDIa/bMDe8bhH4MxHqID7nOKqre', 'Ecole Nationale Supérieure de l Electronique et de ses Applications');
insert into accounts (username, password, university) values ('Nadean', '$2b$10$QI.WvMD7R6DKtKb4FggsTeGmkGMibCPfzd2lFLPD75mxx6nLfTfXq', 'Sardar Vallabhai Patel University of Agriculture Amd Technology');
insert into accounts (username, password, university) values ('Linnet', '$2b$10$hz8W/B4dgJuGkfoncEn8GejJ62jjegx7hluR63xr5ZnL0GCmH7TIS', 'Dirección General de Institutos Tecnológicos');
insert into accounts (username, password, university) values ('Caryl', '$2b$10$rZfZ3V5uei5ALskDRqQAUOGPQCMS23cUvV6udsN9KNAcDmzyoPPs.', 'Université des Sciences Sociales (Toulouse I)');
insert into accounts (username, password, university) values ('Winifield', '$2b$10$MfY3M579IYfPI7fQ7P58j.lKknoDjr.kKoxl4aH2IwMBDLMUdimjO', 'Universidad Madero');
insert into accounts (username, password, university) values ('Terrill', '$2b$10$7W6vBjsBE0.kvFJziB26NeEFDubeUYT8dHURCTm7Gu3jmOwxpBYOq', 'Al-Quds University - The Arab University in Jerusalem');
insert into accounts (username, password, university) values ('Ardeen', '$2b$10$XG/U/REJ/1F9DJmVf70BrOmq.rphjQ446dDN79zZsYwjxGtIlYeGS', 'Université Jean Monnet');
insert into accounts (username, password, university) values ('Tailor', '$2b$10$1vL4qI7Nk6KzT66BMCT1HeKvGeGnBDQyjpqxwW3qpNio.N5wAUU0S', 'Tusculum College');
insert into accounts (username, password, university) values ('Wilmer', '$2b$10$SFJt/bJgRNlvbkstHrvRBurQvO1XizRnVFrEttKS89L9kobb1pC9i', 'Université Shalom de Bunia');
insert into accounts (username, password, university) values ('Win', '$2b$10$jyu5vtZeWlA0GTvjskzneOKhdSijvF.C.M858GaLpfXQh47UIbVzm', 'Ivanovo State Power University');
insert into accounts (username, password, university) values ('Hanan', '$2b$10$Wi4wYBs7Y/zVru46v7fMKeTLczPGJIOukJXfvRErigr8i.chzS622', 'Sana a University');
insert into accounts (username, password, university) values ('Karel', '$2b$10$CfP1nVA72WfWud6YGQKAE.uZAfdcdnIC3J0K/3mnekBKuNmUku45y', 'University of the Visayas');
insert into accounts (username, password, university) values ('Galina', '$2b$10$m4F.2muOBqm7I55.JEaN/OW8BwjpEnvxXjkVhv41zTZQqRHRH5bou', 'Universidade Metodista de Angola');
insert into accounts (username, password, university) values ('Myrtie', '$2b$10$qTYSL7JGpBeY6KyVIP4tn.d2XR/x7O3o9PUiK9pt2ToEda1ZsqVga', 'Agricultural University of Cracow');
insert into accounts (username, password, university) values ('Jesse', '$2b$10$M8ZiNdKrnLp/3hf/ue9W/u24yMRR/Orl/RXxuRvGZ1dttVKypYfQ6', 'College for Lifelong Learning');
insert into accounts (username, password, university) values ('Susann', '$2b$10$AaARkDZ7Vi3kdd07tWw/X.jqp1.qpQKaX8AYZNjw.DSxanngXwik.', 'Tokyo University of Agriculture and Technology');
insert into accounts (username, password, university) values ('Shaina', '$2b$10$xL/8d2dvarblj37sMABQTumDTlKtJDIzlJyqY9YDIrJgFIoyo874.', 'Technological University (Pyay)');
insert into accounts (username, password, university) values ('Yurik', '$2b$10$K2zz8lwPx9hQTH8Tcy99leXsue7ih6tLGZsXGVeoMd7BHbq9NGcK6', 'Universidad Centroamericana');
insert into accounts (username, password, university) values ('Geralda', '$2b$10$NBQ4kaRBZW1Ecq97POL6O.eJqlClfC5BLEtHcGfLS9k3zqtrsNQrK', 'North Kazakhstan State University');
insert into accounts (username, password, university) values ('Erhard', '$2b$10$lfGrSsVTucvbeTIn8bFUwOQcmtG7u1JcAWU7/twyRpUHxM6H2iimC', 'Mahatma Gandhi Chitrakut Gramoday University');
insert into accounts (username, password, university) values ('Brinna', '$2b$10$jJdfCiXSF.nr01JPgojG9u9Kmz7509vLgXZ.m54kNsn9wD88V.1yC', 'Stephen F. Austin State University');
insert into accounts (username, password, university) values ('Sutton', '$2b$10$Ldn3MQnkbrDADp3LRRJB4ed/XfLJOGJi9JhCiRvXQwbsq/9puT15a', 'HWP - Hamburger Universität für Wirtschaft und Politik');
insert into accounts (username, password, university) values ('Chancey', '$2b$10$jMQOtBLQZXkAjqcu7xfbmeKsHcOQK75NlP5liku5w.6ecPCixzzR6', 'Concordia University, River Forest');
insert into accounts (username, password, university) values ('Maxie', '$2b$10$aJn5oTVFk.VcRa/o1SZev.Oz6dBAwaCjLfYulBr6wn58duIGi4i86', 'University of Wisconsin - Stout');
insert into accounts (username, password, university) values ('Lotta', '$2b$10$31VyPXNCugDDw5yPaKLAXOrax00CK8h24jSWzZ5dQMZ8V5livjF9.', 'Ho Chi Minh City Open University');
insert into accounts (username, password, university) values ('Berne', '$2b$10$8RmMwLh7vzVoxyozJGBeT.3EkwGvja24VJsjwUwvFBJEKRQl4YeXG', 'International Bible College');
insert into accounts (username, password, university) values ('Mauricio', '$2b$10$r43a/AAjZjnh9XxW.r7j2.0kz6MWCCWQhzmlGidipgjX3RbAMTfPW', 'Penza State University');
insert into accounts (username, password, university) values ('Celie', '$2b$10$z6fMqgVqafYW2MUIOnoJdepg6MycDeb05pNkLPiwWKzmVn2yMa/Qe', 'Otemae University');
insert into accounts (username, password, university) values ('Olenka', '$2b$10$E0MgkW6dP3DK6vs0v9tRTuDIK8vGuG8jWNv4Mt7FWWcrgqD9Ejh0C', 'Christopher Newport University');
insert into accounts (username, password, university) values ('Ramsay', '$2b$10$uujTZblUdC6TAMvKy9HJCO7SBton5UUri8LPGd5N7CtRn1JN/5pJC', 'New York Institute of Technology');
insert into accounts (username, password, university) values ('Jose', '$2b$10$LmWnnryp9Oohl4ZpcEX/3.oVlAkqRDK5olOjFmLYcotBHxosNsmDi', 'Grand Valley State University');
insert into accounts (username, password, university) values ('Charla', '$2b$10$2qv6wWDjeCJO27wlafMc2eZVpgJnDq.QQUJSBfP2fiuOwNMDGPWbu', 'Université d Oran Es-Senia');
insert into accounts (username, password, university) values ('Bobbye', '$2b$10$uRfLGKzvCf/1vjCx8fiLiOSVjBgMoWBggTweYcPThmZkOLxlkA8Cy', 'Ecole Nationale Vétérinaire d Alfort');
insert into accounts (username, password, university) values ('Timothee', '$2b$10$9fynygY4c63cpWNjgJj5nuRhB8oXvnDN6aBCdi/vhd5prfYJjkLWG', 'Al-Baath University');
insert into accounts (username, password, university) values ('Nelli', '$2b$10$/q7urZjgN7Afkd5cs/zGj.ee6fuv139i6qaNxRa5Iec.yacRC6DOy', 'New England Conservatory of Music');
insert into accounts (username, password, university) values ('Etta', '$2b$10$YBw2WEUKOaSzSMxwpgX2IeEf9x8f3eZCn2zFWnmFdRSdszMoLagyO', 'Institue of Technology, Tralee');
insert into accounts (username, password, university) values ('Dory', '$2b$10$eURbpl1I5VDdJjZqjH3yg.knA1FLgdh6nnkD8yyJX6OLn4L8SVG7G', 'Hochschule Wismar, Fachhochschule für Technik, Wirtschaft und Gestaltung');
insert into accounts (username, password, university) values ('Whitman', '$2b$10$F9aAZXD1oYzRfVND73iXve7MiWL8uO7hujv3.uI1gRvfn1h4nslYG', 'Universitas Muhammadiyah Jember');
insert into accounts (username, password, university) values ('Delainey', '$2b$10$7CDtOKqlDgrL1TaSw.f43u/SbBB/YpPgLnKnIXW.4/hxZh6cSMg2u', 'Aligarh Muslim University');
insert into accounts (username, password, university) values ('Shaine', '$2b$10$Zn6FZDEpaI1x6/Sh3zgwbuLj3EdPaPy4Tdl2r1TISb69q7U9t3.IW', 'Universität Mozarteum Salzburg');
insert into accounts (username, password, university) values ('Freddie', '$2b$10$933R6Xmgz7/9MwMNXlKDzOpDAO1jzT1HzvBUFudqGpOurZt/LRQmq', 'Universidade Estadual Paulista');
insert into accounts (username, password, university) values ('Hephzibah', '$2b$10$9edy6vgtJA94KDAg2kesLOEySRa017MwMx.5rsT8G6cLfs3ju587i', 'Universidad Nacional Experimental Sur del Lago "Jesús Maria Semprum"');
insert into accounts (username, password, university) values ('Bessie', '$2b$10$Wy4hIKWv4DgtrxETSPwJmuutIXFiZ.hXtnUiu.4CkW4JSGO8DyKiO', 'Karnataka State Law University');
insert into accounts (username, password, university) values ('Horatio', '$2b$10$nlG9jNcEb/QWUU9NbYIyKedmUieGA/1MyepxucrrXBUvo9/F4EP22', 'Pennsylvania State University Delaware County');
